links:
  youtube-play: htp:/dfdfsdf/
  shopping-cart: whatever
  twitter: whatever
  instagram: whatever
  soundcloud: whatever
  facebook: whatever
  volume-up: whatever
artists:
  Katelynn Janowski:
    - http://stuff
    - http://google.com/
  Marjorie Kimbrel:
    - http://stuff
    - http://google.com/
  Loria Hargraves:
    - http://stuff
    - http://google.com/
  Billy Broder:
    - http://stuff
    - http://google.com/
  Lyla Frenkel:
    - http://stuff
    - http://google.com/
  Peter Quin:
    - http://stuff
    - http://google.com/
  Shaunna Bierbaum:
    - http://stuff
    - http://google.com/
  Temika Whitfield:
    - http://stuff
    - http://google.com/
  Sonja Mcamis:
    - http://stuff
    - http://google.com/
  Luana Cabral:
    - http://stuff
    - http://google.com/
  Carla Yohe:
    - http://stuff
    - http://google.com/
  Merilyn Curnutte:
    - http://stuff
    - http://google.com/
  Suzan Estep:
    - http://stuff
    - http://google.com/
  Jenifer Polly:
    - http://stuff
    - http://google.com/
  Tijuana Marshall:
    - http://stuff
    - http://google.com/
  Louella Enochs:
    - http://stuff
    - http://google.com/
  Devon Stclair:
    - http://stuff
    - http://google.com/
  Horace Hedberg:
    - http://stuff
    - http://google.com/
  Della Schnabel:
    - http://stuff
    - http://google.com/
  Saul Shanabrook:
    - http://blahblah
  God:
    - http:/helpme/
    - http:/helpme/
    - http:/helpme/
